// Generated by dts-bundle-generator v6.2.0

/// <reference types="emscripten" />
/// <reference types="node" />

export declare type FFTWModuleFactory = EmscriptenModuleFactory<FFTWModule>;
export interface FFTWModule extends EmscriptenModule {
	ccall: typeof ccall;
	cwrap: typeof cwrap;
	_fftwf_plan_dft_r2c_1d: (n: number, $in: number, $out: number, flags: number) => number;
	_fftwf_plan_dft_c2r_1d: (n: number, $in: number, $out: number, flags: number) => number;
	_fftwf_plan_r2r_1d: (n: number, $in: number, $out: number, kind: number, flags: number) => number;
	_fftwf_plan_r2r_2d: (n0: number, n1: number, $in: number, $out: number, kind0: number, kind1: number, flags: number) => number;
	_fftwf_plan_dft_1d: (n: number, $in: number, $out: number, sign: number, flags: number) => number;
	_fftwf_plan_dft_2d: (n0: number, n1: number, $in: number, $out: number, sign: number, flags: number) => number;
	_fftwf_execute: ($plan: number) => void;
	_fftwf_destroy_plan: ($plan: number) => void;
	_fftwf_free: ($: number) => void;
	_fftwf_malloc: (size: number) => number;
}
export interface FFT {
	forward(arr: ArrayLike<number> | ((arr: Float32Array) => any)): Float32Array;
	inverse(arr: ArrayLike<number> | ((arr: Float32Array) => any)): Float32Array;
	dispose(): void;
}
export declare const FFTWModuleFactoryFn: FFTWModuleFactory;
export declare const FFTWModuleFactoryWasm: Uint8Array;
/**
 * Instantiate EMCC Module using bundled binaries. Module constructor and files can be overriden.
 */
export declare const instantiateFFTWModule: (ModuleFactoryIn?: FFTWModuleFactory, wasmBinaryIn?: Uint8Array) => Promise<FFTWModule>;
/**
 * Load emcc-wasm files, than instantiate it
 * @param jsFile path to `emcc-wasm.js`
 * @param wasmFile path to `emcc-wasm.wasm`
 * @param dataFile path to `emcc-wasm.data`
 */
export declare const instantiateFFTWModuleFromFile: (jsFile: string, wasmFile?: string, dataFile?: string) => Promise<FFTWModule>;
export declare class FFTW {
	c2c: {
		FFT1D: new (size: number) => FFT;
		FFT2D: new (n0: number, n1: number) => FFT;
	};
	r2c: {
		FFT1D: new (size: number) => FFT;
	};
	r2r: {
		FFT1D: new (size: number) => FFT;
		DCT1D: new (size: number) => FFT;
		DST1D: new (size: number) => FFT;
		FFT2D: new (n0: number, n1: number) => FFT;
		DCT2D: new (n0: number, n1: number) => FFT;
		DST2D: new (n0: number, n1: number) => FFT;
	};
	constructor(fftwModule: FFTWModule);
}

export {};
